### ISSUE TITLE
Using ChromaPreference in PreferenceFragment

### ISSUE THREAD

**Issue by mcfly83** [MrBIMC/VintageChroma#12]
I'm trying to use a ChromaPreference in my PreferenceActivity. This fails at runtime when clicking the preference because it seems to expect an AppCompatActivity.

Here's the stacktrace:
java.lang.ClassCastException: com.test.SettingsActivity cannot be cast to android.support.v7.app.AppCompatActivity
                                                                       at com.pavelsikun.vintagechroma.ChromaPreference.onClick(ChromaPreference.java:128)
                                                                       at android.preference.Preference.performClick(Preference.java:994)
                                                                       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                       at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Am I doing something wrong or is this simply not supported?

On a side note: Is there any way to disable displaying the color as the preference summary? I need to display some helpful string there.

Thanks in advance

**Comment by MrBIMC** [comment]
What type of activity do you use? This lib() requires AppCompat as it calls for getSupportFragmentManager() which is available only in AppCompatActivity. Checkout sample project, it explains it fairly well.

On a side note: I will add option for custom summary in the next update.

**Comment by mcfly83** [comment]
It's a simple PreferenceAcitity (https://developer.android.com/reference/android/preference/PreferenceActivity.html), nothing special.

Thanks a lot for the summary option!

**Comment by ARCofSpada** [comment]
I also have this issue

This is my code inside a preference activity:
`<com.pavelsikun.vintagechroma.ChromaPreference
            android:key="pref_dark_theme_guilds"
            android:title="@string/pref_title_color_guilds"
            app:chromaColorMode="ARGB"
            app:chromaIndicatorMode="HEX"
            app:chromaInitialColor="@color/theme_grey_guilds"/>
`
After I get
`FATAL EXCEPTION: main
                                                                         Process: ws.rhythm.xapp, PID: 14498
                                                                         Theme: themes:{com.android.systemui.headers=overlay:com.spastef.inversion, default=overlay:com.spastef.inversion, fontPkg:system, com.android.systemui=overlay:com.spastef.inversion, com.android.systemui.navbar=overlay:com.n78shadow.nstyleblue}
                                                                         java.lang.ClassCastException: ws.rhythm.xapp.SettingsActivity cannot be cast to android.support.v7.app.AppCompatActivity
                                                                             at com.pavelsikun.vintagechroma.ChromaPreference.onClick(ChromaPreference.java:128)
                                                                             at android.preference.Preference.performClick(Preference.java:994)
                                                                             at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                             at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                             at android.widget.AbsListView.performItemClick(AbsListView.java:1183)
                                                                             at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
                                                                             at android.widget.AbsListView$4.run(AbsListView.java:4076)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5475)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by carvalho2707** [comment]
I have the same error. I can't use this in a Simple Preference activity ( the one generated by google)

public class SettingsActivity extends AppCompatPreferenceActivity
